[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200

build_flags =
  -D BLE_DEVICE_NAME=\"HRM_SIM_05\"
  -D BLE_USE_CUSTOM_BASE_MAC=1
  -D BLE_BASE_MAC_0=0x02
  -D BLE_BASE_MAC_1=0xAA
  -D BLE_BASE_MAC_2=0xBB
  -D BLE_BASE_MAC_3=0xCC
  -D BLE_BASE_MAC_4=0xDD
  -D BLE_BASE_MAC_5=0x05

; If your board is ESP32-S3, switch to:
; board = esp32-s3-devkitc-1



