// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: rowing480320

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 480);
    lv_obj_set_height(ui_Panel1, 50);
    lv_obj_set_x(ui_Panel1, -1);
    lv_obj_set_y(ui_Panel1, -136);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_Image5, &ui_img_stopwatch_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, 1);
    lv_obj_set_y(ui_Image5, 0);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 200);

    ui_Label10 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 197);
    lv_obj_set_y(ui_Label10, -1);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "20:38");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -186);
    lv_obj_set_y(ui_Label15, -12);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "00");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_Fon13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label51 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, -172);
    lv_obj_set_y(ui_Label51, -12);
    lv_obj_set_align(ui_Label51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label51, "-");
    lv_obj_set_style_text_color(ui_Label51, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label51, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label51, &ui_font_Fon13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -157);
    lv_obj_set_y(ui_Label16, -12);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "00");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_Fon13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_Image1, &ui_img_jieli1_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -127);
    lv_obj_set_y(ui_Image1, 0);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 200);

    ui_Label43 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, -186);
    lv_obj_set_y(ui_Label43, 9);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "");
    lv_obj_set_style_text_color(ui_Label43, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label43, &ui_font_Fon13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label65 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label65, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label65, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label65, -87);
    lv_obj_set_y(ui_Label65, 8);
    lv_obj_set_align(ui_Label65, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label65, "");
    lv_obj_set_style_text_color(ui_Label65, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label65, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label65, &ui_font_Fon13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label58 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label58, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label58, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label58, -93);
    lv_obj_set_y(ui_Label58, -11);
    lv_obj_set_align(ui_Label58, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label58, "");
    lv_obj_set_style_text_color(ui_Label58, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label58, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label58, &ui_font_Font17, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label61 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label61, -32);
    lv_obj_set_y(ui_Label61, -12);
    lv_obj_set_align(ui_Label61, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label61, "0");
    lv_obj_set_style_text_color(ui_Label61, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label61, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label61, &ui_font_Fon13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_Image2, &ui_img_ble1_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 43
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_Image2, -53);
    lv_obj_set_y(ui_Image2, -1);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 200);

    ui_Container1 = lv_obj_create(ui_Panel1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 47);
    lv_obj_set_height(ui_Container1, 24);
    lv_obj_set_x(ui_Container1, 127);
    lv_obj_set_y(ui_Container1, -1);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_battery1 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_battery1, 4);
    lv_obj_set_height(ui_battery1, 20);
    lv_obj_set_x(ui_battery1, -20);
    lv_obj_set_y(ui_battery1, 1);
    lv_obj_set_align(ui_battery1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_battery1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_battery1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_battery1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_battery1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery2 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_battery2, 4);
    lv_obj_set_height(ui_battery2, 20);
    lv_obj_set_x(ui_battery2, 10);
    lv_obj_set_y(ui_battery2, 1);
    lv_obj_set_align(ui_battery2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_battery2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_battery2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_battery2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_battery2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery3 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_battery3, 34);
    lv_obj_set_height(ui_battery3, 4);
    lv_obj_set_x(ui_battery3, -5);
    lv_obj_set_y(ui_battery3, -7);
    lv_obj_set_align(ui_battery3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_battery3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_battery3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_battery3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_battery3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery4 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_battery4, 34);
    lv_obj_set_height(ui_battery4, 4);
    lv_obj_set_x(ui_battery4, -5);
    lv_obj_set_y(ui_battery4, 9);
    lv_obj_set_align(ui_battery4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_battery4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_battery4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_battery4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_battery4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery5 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_battery5, 4);
    lv_obj_set_height(ui_battery5, 10);
    lv_obj_set_x(ui_battery5, 14);
    lv_obj_set_y(ui_battery5, 1);
    lv_obj_set_align(ui_battery5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_battery5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_battery5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_battery5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_battery5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery6parent = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_battery6parent, 4);
    lv_obj_set_height(ui_battery6parent, 8);
    lv_obj_set_x(ui_battery6parent, -14);
    lv_obj_set_y(ui_battery6parent, 1);
    lv_obj_set_align(ui_battery6parent, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_battery6parent, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_battery6parent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_battery6parent, lv_color_hex(0xA1A1A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_battery6parent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery7parent = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_battery7parent, 4);
    lv_obj_set_height(ui_battery7parent, 8);
    lv_obj_set_x(ui_battery7parent, -8);
    lv_obj_set_y(ui_battery7parent, 1);
    lv_obj_set_align(ui_battery7parent, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_battery7parent, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_battery7parent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_battery7parent, lv_color_hex(0xA1A1A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_battery7parent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery8parent = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_battery8parent, 4);
    lv_obj_set_height(ui_battery8parent, 8);
    lv_obj_set_x(ui_battery8parent, -2);
    lv_obj_set_y(ui_battery8parent, 1);
    lv_obj_set_align(ui_battery8parent, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_battery8parent, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_battery8parent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_battery8parent, lv_color_hex(0xA1A1A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_battery8parent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery9parent = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_battery9parent, 4);
    lv_obj_set_height(ui_battery9parent, 8);
    lv_obj_set_x(ui_battery9parent, 4);
    lv_obj_set_y(ui_battery9parent, 1);
    lv_obj_set_align(ui_battery9parent, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_battery9parent, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_battery9parent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_battery9parent, lv_color_hex(0xA1A1A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_battery9parent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery6on = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_battery6on, 4);
    lv_obj_set_height(ui_battery6on, 8);
    lv_obj_set_x(ui_battery6on, -14);
    lv_obj_set_y(ui_battery6on, 1);
    lv_obj_set_align(ui_battery6on, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_battery6on, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_battery6on, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_battery6on, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_battery6on, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_battery6on, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_battery6on, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery7on = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_battery7on, 4);
    lv_obj_set_height(ui_battery7on, 8);
    lv_obj_set_x(ui_battery7on, -8);
    lv_obj_set_y(ui_battery7on, 1);
    lv_obj_set_align(ui_battery7on, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_battery7on, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_battery7on, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_battery7on, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_battery7on, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_battery7on, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_battery7on, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_battery7on, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_battery7on, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery8on = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_battery8on, 4);
    lv_obj_set_height(ui_battery8on, 8);
    lv_obj_set_x(ui_battery8on, -2);
    lv_obj_set_y(ui_battery8on, 1);
    lv_obj_set_align(ui_battery8on, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_battery8on, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_battery8on, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_battery8on, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_battery8on, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_battery8on, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_battery8on, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_battery8on, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_battery8on, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery9on = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_battery9on, 4);
    lv_obj_set_height(ui_battery9on, 8);
    lv_obj_set_x(ui_battery9on, 4);
    lv_obj_set_y(ui_battery9on, 1);
    lv_obj_set_align(ui_battery9on, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_battery9on, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_battery9on, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_battery9on, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_battery9on, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_battery9on, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_battery9on, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_battery9on, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_battery9on, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Panel1);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 33);
    lv_obj_set_height(ui_Container4, 35);
    lv_obj_set_x(ui_Container4, 86);
    lv_obj_set_y(ui_Container4, 1);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sig1bar1parent2 = lv_obj_create(ui_Container4);
    lv_obj_set_width(ui_sig1bar1parent2, 4);
    lv_obj_set_height(ui_sig1bar1parent2, 8);
    lv_obj_set_x(ui_sig1bar1parent2, -9);
    lv_obj_set_y(ui_sig1bar1parent2, 6);
    lv_obj_set_align(ui_sig1bar1parent2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sig1bar1parent2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_sig1bar1parent2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sig1bar1parent2, lv_color_hex(0xA1A1A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sig1bar1parent2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sig1bar1parent2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sig1bar2parent2 = lv_obj_create(ui_Container4);
    lv_obj_set_width(ui_sig1bar2parent2, 4);
    lv_obj_set_height(ui_sig1bar2parent2, 13);
    lv_obj_set_x(ui_sig1bar2parent2, -3);
    lv_obj_set_y(ui_sig1bar2parent2, 3);
    lv_obj_set_align(ui_sig1bar2parent2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sig1bar2parent2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_sig1bar2parent2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sig1bar2parent2, lv_color_hex(0xA1A1A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sig1bar2parent2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sig1bar2parent2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sig1bar3parent2 = lv_obj_create(ui_Container4);
    lv_obj_set_width(ui_sig1bar3parent2, 4);
    lv_obj_set_height(ui_sig1bar3parent2, 18);
    lv_obj_set_x(ui_sig1bar3parent2, 3);
    lv_obj_set_y(ui_sig1bar3parent2, 1);
    lv_obj_set_align(ui_sig1bar3parent2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sig1bar3parent2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_sig1bar3parent2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sig1bar3parent2, lv_color_hex(0xA1A1A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sig1bar3parent2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sig1bar3parent2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sig1bar4parent2 = lv_obj_create(ui_Container4);
    lv_obj_set_width(ui_sig1bar4parent2, 4);
    lv_obj_set_height(ui_sig1bar4parent2, 23);
    lv_obj_set_x(ui_sig1bar4parent2, 9);
    lv_obj_set_y(ui_sig1bar4parent2, -2);
    lv_obj_set_align(ui_sig1bar4parent2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sig1bar4parent2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_sig1bar4parent2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sig1bar4parent2, lv_color_hex(0xA1A1A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sig1bar4parent2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sig1bar4parent2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sig1bar1on2 = lv_obj_create(ui_Container4);
    lv_obj_set_width(ui_sig1bar1on2, 4);
    lv_obj_set_height(ui_sig1bar1on2, 8);
    lv_obj_set_x(ui_sig1bar1on2, -9);
    lv_obj_set_y(ui_sig1bar1on2, 6);
    lv_obj_set_align(ui_sig1bar1on2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sig1bar1on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_sig1bar1on2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sig1bar1on2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sig1bar1on2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sig1bar1on2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sig1bar2on2 = lv_obj_create(ui_Container4);
    lv_obj_set_width(ui_sig1bar2on2, 4);
    lv_obj_set_height(ui_sig1bar2on2, 13);
    lv_obj_set_x(ui_sig1bar2on2, -3);
    lv_obj_set_y(ui_sig1bar2on2, 3);
    lv_obj_set_align(ui_sig1bar2on2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sig1bar2on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_sig1bar2on2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sig1bar2on2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sig1bar2on2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sig1bar2on2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sig1bar3on2 = lv_obj_create(ui_Container4);
    lv_obj_set_width(ui_sig1bar3on2, 4);
    lv_obj_set_height(ui_sig1bar3on2, 18);
    lv_obj_set_x(ui_sig1bar3on2, 3);
    lv_obj_set_y(ui_sig1bar3on2, 1);
    lv_obj_set_align(ui_sig1bar3on2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sig1bar3on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_sig1bar3on2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sig1bar3on2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sig1bar3on2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sig1bar3on2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sig1bar4on2 = lv_obj_create(ui_Container4);
    lv_obj_set_width(ui_sig1bar4on2, 4);
    lv_obj_set_height(ui_sig1bar4on2, 23);
    lv_obj_set_x(ui_sig1bar4on2, 9);
    lv_obj_set_y(ui_sig1bar4on2, -2);
    lv_obj_set_align(ui_sig1bar4on2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sig1bar4on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_sig1bar4on2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sig1bar4on2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sig1bar4on2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sig1bar4on2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 150);
    lv_obj_set_y(ui_Label19, 0);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "");
    lv_obj_add_flag(ui_Label19, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &ui_font_Fon13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_Image6, &ui_img_798663736);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Image6, 79);
    lv_obj_set_y(ui_Image6, -8);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_Image4, &ui_img_2127489813);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_Image4, 151);
    lv_obj_set_y(ui_Image4, 0);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 200);

    ui_Image7 = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_Image7, &ui_img_satellite2_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image7, -217);
    lv_obj_set_y(ui_Image7, 0);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label33 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, 48);
    lv_obj_set_y(ui_Label33, 2);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "");
    lv_obj_set_style_text_color(ui_Label33, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label33, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 242);
    lv_obj_set_height(ui_Panel2, 137);
    lv_obj_set_x(ui_Panel2, -120);
    lv_obj_set_y(ui_Panel2, -45);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "0.0");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Font50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -94);
    lv_obj_set_y(ui_Label2, -52);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "桨频");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 90);
    lv_obj_set_y(ui_Label28, 53);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "/min");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label28, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 240);
    lv_obj_set_height(ui_Panel3, 137);
    lv_obj_set_x(ui_Panel3, 119);
    lv_obj_set_y(ui_Panel3, -45);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "00:00..0");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Font50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label98 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label98, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label98, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label98, -93);
    lv_obj_set_y(ui_Label98, -52);
    lv_obj_set_align(ui_Label98, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label98, "配速");
    lv_obj_set_style_text_color(ui_Label98, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label98, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label98, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 80);
    lv_obj_set_y(ui_Label29, 53);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "/500m");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label29, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_P1Timer = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_P1Timer, 242);
    lv_obj_set_height(ui_P1Timer, 138);
    lv_obj_set_x(ui_P1Timer, -120);
    lv_obj_set_y(ui_P1Timer, 91);
    lv_obj_set_align(ui_P1Timer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_P1Timer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_P1Timer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_P1Timer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_P1Timer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_P1Timer);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "00:00");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Font50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label99 = lv_label_create(ui_P1Timer);
    lv_obj_set_width(ui_Label99, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label99, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label99, -94);
    lv_obj_set_y(ui_Label99, -53);
    lv_obj_set_align(ui_Label99, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label99, "计时");
    lv_obj_set_style_text_color(ui_Label99, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label99, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label99, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_P1Split = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_P1Split, 242);
    lv_obj_set_height(ui_P1Split, 138);
    lv_obj_set_x(ui_P1Split, -120);
    lv_obj_set_y(ui_P1Split, 91);
    lv_obj_set_align(ui_P1Split, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_P1Split, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_P1Split, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_P1Split, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_P1Split, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_P1Split, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_P1Split);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "0.0");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_Font50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_P1Split);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -94);
    lv_obj_set_y(ui_Label1, -53);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "划距");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_P1Split);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 106);
    lv_obj_set_y(ui_Label21, 53);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "m");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_P1Dist = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_P1Dist, 242);
    lv_obj_set_height(ui_P1Dist, 138);
    lv_obj_set_x(ui_P1Dist, -120);
    lv_obj_set_y(ui_P1Dist, 91);
    lv_obj_set_align(ui_P1Dist, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_P1Dist, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_P1Dist, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_P1Dist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_P1Dist, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_P1Dist, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_P1Dist);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "0.000");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &ui_font_Font50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_P1Dist);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -94);
    lv_obj_set_y(ui_Label6, -53);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "距离");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_P1Dist);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 100);
    lv_obj_set_y(ui_Label24, 53);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "km");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_P1Stroke = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_P1Stroke, 242);
    lv_obj_set_height(ui_P1Stroke, 138);
    lv_obj_set_x(ui_P1Stroke, -120);
    lv_obj_set_y(ui_P1Stroke, 91);
    lv_obj_set_align(ui_P1Stroke, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_P1Stroke, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_P1Stroke, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_P1Stroke, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_P1Stroke, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_P1Stroke, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label44 = lv_label_create(ui_P1Stroke);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "0");
    lv_obj_set_style_text_color(ui_Label44, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label44, &ui_font_Font50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_P1Stroke);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -94);
    lv_obj_set_y(ui_Label3, -53);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "桨数");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_P1Speed = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_P1Speed, 242);
    lv_obj_set_height(ui_P1Speed, 138);
    lv_obj_set_x(ui_P1Speed, -120);
    lv_obj_set_y(ui_P1Speed, 91);
    lv_obj_set_align(ui_P1Speed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_P1Speed, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_P1Speed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_P1Speed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_P1Speed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_P1Speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label46 = lv_label_create(ui_P1Speed);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "0.0");
    lv_obj_set_style_text_color(ui_Label46, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label46, &ui_font_Font50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label92 = lv_label_create(ui_P1Speed);
    lv_obj_set_width(ui_Label92, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label92, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label92, -94);
    lv_obj_set_y(ui_Label92, -53);
    lv_obj_set_align(ui_Label92, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label92, "速度");
    lv_obj_set_style_text_color(ui_Label92, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label92, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label92, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_P1Speed);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 95);
    lv_obj_set_y(ui_Label25, 53);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "m/s");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_P1Power = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_P1Power, 242);
    lv_obj_set_height(ui_P1Power, 138);
    lv_obj_set_x(ui_P1Power, -120);
    lv_obj_set_y(ui_P1Power, 91);
    lv_obj_set_align(ui_P1Power, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_P1Power, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_P1Power, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_P1Power, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_P1Power, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_P1Power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label48 = lv_label_create(ui_P1Power);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "0");
    lv_obj_set_style_text_color(ui_Label48, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label48, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label48, &ui_font_Font50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label97 = lv_label_create(ui_P1Power);
    lv_obj_set_width(ui_Label97, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label97, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label97, -94);
    lv_obj_set_y(ui_Label97, -53);
    lv_obj_set_align(ui_Label97, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label97, "功率");
    lv_obj_set_style_text_color(ui_Label97, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label97, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label97, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_P1Power);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 106);
    lv_obj_set_y(ui_Label26, 53);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "W");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label26, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_P1HR = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_P1HR, 242);
    lv_obj_set_height(ui_P1HR, 138);
    lv_obj_set_x(ui_P1HR, -120);
    lv_obj_set_y(ui_P1HR, 91);
    lv_obj_set_align(ui_P1HR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_P1HR, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_P1HR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_P1HR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_P1HR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_P1HR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label50 = lv_label_create(ui_P1HR);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "0");
    lv_obj_set_style_text_color(ui_Label50, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label50, &ui_font_Font50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label88 = lv_label_create(ui_P1HR);
    lv_obj_set_width(ui_Label88, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label88, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label88, -94);
    lv_obj_set_y(ui_Label88, -53);
    lv_obj_set_align(ui_Label88, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label88, "心率");
    lv_obj_set_style_text_color(ui_Label88, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label88, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label88, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_P1HR);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 92);
    lv_obj_set_y(ui_Label27, 53);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "bmp");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_P1HR);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label53, 84);
    lv_obj_set_y(ui_Label53, -53);
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "未选择");
    lv_obj_set_style_text_color(ui_Label53, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label53, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label53, &ui_font_Font23, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_P8Dist = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_P8Dist, 240);
    lv_obj_set_height(ui_P8Dist, 138);
    lv_obj_set_x(ui_P8Dist, 119);
    lv_obj_set_y(ui_P8Dist, 91);
    lv_obj_set_align(ui_P8Dist, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_P8Dist, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_P8Dist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_P8Dist, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_P8Dist, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label60 = lv_label_create(ui_P8Dist);
    lv_obj_set_width(ui_Label60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label60, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label60, "0.000");
    lv_obj_set_style_text_color(ui_Label60, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label60, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label60, &ui_font_Font50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label100 = lv_label_create(ui_P8Dist);
    lv_obj_set_width(ui_Label100, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label100, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label100, -93);
    lv_obj_set_y(ui_Label100, -53);
    lv_obj_set_align(ui_Label100, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label100, "距离");
    lv_obj_set_style_text_color(ui_Label100, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label100, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label100, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label87 = lv_label_create(ui_P8Dist);
    lv_obj_set_width(ui_Label87, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label87, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label87, 99);
    lv_obj_set_y(ui_Label87, 53);
    lv_obj_set_align(ui_Label87, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label87, "km");
    lv_obj_set_style_text_color(ui_Label87, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label87, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label87, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_P8Stroke = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_P8Stroke, 240);
    lv_obj_set_height(ui_P8Stroke, 138);
    lv_obj_set_x(ui_P8Stroke, 119);
    lv_obj_set_y(ui_P8Stroke, 91);
    lv_obj_set_align(ui_P8Stroke, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_P8Stroke, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_P8Stroke, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_P8Stroke, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_P8Stroke, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_P8Stroke, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label64 = lv_label_create(ui_P8Stroke);
    lv_obj_set_width(ui_Label64, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label64, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label64, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label64, "0");
    lv_obj_set_style_text_color(ui_Label64, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label64, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label64, &ui_font_Font50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label94 = lv_label_create(ui_P8Stroke);
    lv_obj_set_width(ui_Label94, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label94, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label94, -93);
    lv_obj_set_y(ui_Label94, -53);
    lv_obj_set_align(ui_Label94, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label94, "桨数");
    lv_obj_set_style_text_color(ui_Label94, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label94, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label94, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_P8Speed = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_P8Speed, 240);
    lv_obj_set_height(ui_P8Speed, 138);
    lv_obj_set_x(ui_P8Speed, 119);
    lv_obj_set_y(ui_P8Speed, 91);
    lv_obj_set_align(ui_P8Speed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_P8Speed, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_P8Speed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_P8Speed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_P8Speed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_P8Speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label68 = lv_label_create(ui_P8Speed);
    lv_obj_set_width(ui_Label68, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label68, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label68, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label68, "0.0");
    lv_obj_set_style_text_color(ui_Label68, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label68, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label68, &ui_font_Font50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label93 = lv_label_create(ui_P8Speed);
    lv_obj_set_width(ui_Label93, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label93, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label93, -93);
    lv_obj_set_y(ui_Label93, -53);
    lv_obj_set_align(ui_Label93, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label93, "速度");
    lv_obj_set_style_text_color(ui_Label93, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label93, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label93, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_P8Speed);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 94);
    lv_obj_set_y(ui_Label11, 53);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "m/s");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_P8Power = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_P8Power, 240);
    lv_obj_set_height(ui_P8Power, 138);
    lv_obj_set_x(ui_P8Power, 119);
    lv_obj_set_y(ui_P8Power, 91);
    lv_obj_set_align(ui_P8Power, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_P8Power, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_P8Power, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_P8Power, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_P8Power, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_P8Power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label72 = lv_label_create(ui_P8Power);
    lv_obj_set_width(ui_Label72, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label72, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label72, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label72, "0");
    lv_obj_set_style_text_color(ui_Label72, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label72, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label72, &ui_font_Font50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label90 = lv_label_create(ui_P8Power);
    lv_obj_set_width(ui_Label90, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label90, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label90, -93);
    lv_obj_set_y(ui_Label90, -53);
    lv_obj_set_align(ui_Label90, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label90, "功率");
    lv_obj_set_style_text_color(ui_Label90, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label90, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label90, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label91 = lv_label_create(ui_P8Power);
    lv_obj_set_width(ui_Label91, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label91, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label91, 105);
    lv_obj_set_y(ui_Label91, 53);
    lv_obj_set_align(ui_Label91, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label91, "W");
    lv_obj_set_style_text_color(ui_Label91, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label91, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label91, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_P8HR = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_P8HR, 240);
    lv_obj_set_height(ui_P8HR, 138);
    lv_obj_set_x(ui_P8HR, 119);
    lv_obj_set_y(ui_P8HR, 91);
    lv_obj_set_align(ui_P8HR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_P8HR, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_P8HR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_P8HR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_P8HR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_P8HR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_P8HR);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "0");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Font50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_P8HR);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -93);
    lv_obj_set_y(ui_Label18, -53);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "心率");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_P8HR);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 91);
    lv_obj_set_y(ui_Label17, 53);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "bmp");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_P8HR);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 81);
    lv_obj_set_y(ui_Label14, -52);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "未选择");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_Font23, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_P8Timer = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_P8Timer, 240);
    lv_obj_set_height(ui_P8Timer, 138);
    lv_obj_set_x(ui_P8Timer, 119);
    lv_obj_set_y(ui_P8Timer, 91);
    lv_obj_set_align(ui_P8Timer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_P8Timer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_P8Timer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_P8Timer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_P8Timer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_P8Timer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_P8Timer);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "00:00");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_Font50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_P8Timer);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -93);
    lv_obj_set_y(ui_Label20, -53);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "计时");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_P8Split = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_P8Split, 240);
    lv_obj_set_height(ui_P8Split, 138);
    lv_obj_set_x(ui_P8Split, 119);
    lv_obj_set_y(ui_P8Split, 91);
    lv_obj_set_align(ui_P8Split, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_P8Split, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_P8Split, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_P8Split, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_P8Split, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_P8Split, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label54 = lv_label_create(ui_P8Split);
    lv_obj_set_width(ui_Label54, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label54, -93);
    lv_obj_set_y(ui_Label54, -53);
    lv_obj_set_align(ui_Label54, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label54, "划距");
    lv_obj_set_style_text_color(ui_Label54, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label54, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label54, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label55 = lv_label_create(ui_P8Split);
    lv_obj_set_width(ui_Label55, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label55, 105);
    lv_obj_set_y(ui_Label55, 53);
    lv_obj_set_align(ui_Label55, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label55, "m");
    lv_obj_set_style_text_color(ui_Label55, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label55, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label55, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label56 = lv_label_create(ui_P8Split);
    lv_obj_set_width(ui_Label56, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label56, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label56, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label56, "0.0");
    lv_obj_set_style_text_color(ui_Label56, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label56, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label56, &ui_font_Font50, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
