// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: rowing480320

#ifndef _ROWING480320_UI_H
#define _ROWING480320_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Label65;
extern lv_obj_t * ui_Label58;
extern lv_obj_t * ui_Label61;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_battery1;
extern lv_obj_t * ui_battery2;
extern lv_obj_t * ui_battery3;
extern lv_obj_t * ui_battery4;
extern lv_obj_t * ui_battery5;
extern lv_obj_t * ui_battery6parent;
extern lv_obj_t * ui_battery7parent;
extern lv_obj_t * ui_battery8parent;
extern lv_obj_t * ui_battery9parent;
extern lv_obj_t * ui_battery6on;
extern lv_obj_t * ui_battery7on;
extern lv_obj_t * ui_battery8on;
extern lv_obj_t * ui_battery9on;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_sig1bar1parent2;
extern lv_obj_t * ui_sig1bar2parent2;
extern lv_obj_t * ui_sig1bar3parent2;
extern lv_obj_t * ui_sig1bar4parent2;
extern lv_obj_t * ui_sig1bar1on2;
extern lv_obj_t * ui_sig1bar2on2;
extern lv_obj_t * ui_sig1bar3on2;
extern lv_obj_t * ui_sig1bar4on2;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label98;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_P1Timer;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label99;
extern lv_obj_t * ui_P1Split;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_P1Dist;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_P1Stroke;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_P1Speed;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Label92;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_P1Power;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Label97;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_P1HR;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Label88;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_P8Dist;
extern lv_obj_t * ui_Label60;
extern lv_obj_t * ui_Label100;
extern lv_obj_t * ui_Label87;
extern lv_obj_t * ui_P8Stroke;
extern lv_obj_t * ui_Label64;
extern lv_obj_t * ui_Label94;
extern lv_obj_t * ui_P8Speed;
extern lv_obj_t * ui_Label68;
extern lv_obj_t * ui_Label93;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_P8Power;
extern lv_obj_t * ui_Label72;
extern lv_obj_t * ui_Label90;
extern lv_obj_t * ui_Label91;
extern lv_obj_t * ui_P8HR;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_P8Timer;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_P8Split;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_Label55;
extern lv_obj_t * ui_Label56;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label31;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel8;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label37;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label38;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label30;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_uiBTListContainer;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label36;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Label80;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Label81;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Label82;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Label89;
extern lv_obj_t * ui_Label83;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Label84;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_stopwatch_png);    // assets/stopwatch.png
LV_IMG_DECLARE(ui_img_jieli1_png);    // assets/jieli1.png
LV_IMG_DECLARE(ui_img_ble1_png);    // assets/ble1.png
LV_IMG_DECLARE(ui_img_798663736);    // assets/sort-outlined.png
LV_IMG_DECLARE(ui_img_2127489813);    // assets/material-symbols--bolt-rounded.png
LV_IMG_DECLARE(ui_img_satellite2_png);    // assets/satellite2.png

// FONTS
LV_FONT_DECLARE(ui_font_Fon13);
LV_FONT_DECLARE(ui_font_Font17);
LV_FONT_DECLARE(ui_font_Font18);
LV_FONT_DECLARE(ui_font_Font20);
LV_FONT_DECLARE(ui_font_Font22);
LV_FONT_DECLARE(ui_font_Font23);
LV_FONT_DECLARE(ui_font_Font24);
LV_FONT_DECLARE(ui_font_Font50);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
