// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: rowing480320

#ifndef _UI_COMP_PANEL4_H
#define _UI_COMP_PANEL4_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Panel4
#define UI_COMP_PANEL4_PANEL4 0
#define UI_COMP_PANEL4_BUTTON3 1
#define UI_COMP_PANEL4_BUTTON3_LABEL47 2
#define UI_COMP_PANEL4_BUTTON5 3
#define UI_COMP_PANEL4_BUTTON5_LABEL37 4
#define _UI_COMP_PANEL4_NUM 5
lv_obj_t * ui_Panel4_create(lv_obj_t * comp_parent);
void ui_event_comp_Panel4_Button3(lv_event_t * e);
void ui_event_comp_Panel4_Button5(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
