// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: rowing480320

#include "ui.h"
#include "ui_helpers.h"

// Force display actual color depth value
#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)
#pragma message("LV_COLOR_DEPTH = " STRINGIZE_VALUE_OF(LV_COLOR_DEPTH))

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t *e);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Image5;
lv_obj_t *ui_Label10;
lv_obj_t *ui_Label15;
lv_obj_t *ui_Label51;
lv_obj_t *ui_Label16;
lv_obj_t *ui_Image1;
lv_obj_t *ui_Label43;
lv_obj_t *ui_Label65;
lv_obj_t *ui_Label58;
lv_obj_t *ui_Label61;
lv_obj_t *ui_Image2;
lv_obj_t *ui_Container1;
lv_obj_t *ui_battery1;
lv_obj_t *ui_battery2;
lv_obj_t *ui_battery3;
lv_obj_t *ui_battery4;
lv_obj_t *ui_battery5;
lv_obj_t *ui_battery6parent;
lv_obj_t *ui_battery7parent;
lv_obj_t *ui_battery8parent;
lv_obj_t *ui_battery9parent;
lv_obj_t *ui_battery6on;
lv_obj_t *ui_battery7on;
lv_obj_t *ui_battery8on;
lv_obj_t *ui_battery9on;
lv_obj_t *ui_Container4;
lv_obj_t *ui_sig1bar1parent2;
lv_obj_t *ui_sig1bar2parent2;
lv_obj_t *ui_sig1bar3parent2;
lv_obj_t *ui_sig1bar4parent2;
lv_obj_t *ui_sig1bar1on2;
lv_obj_t *ui_sig1bar2on2;
lv_obj_t *ui_sig1bar3on2;
lv_obj_t *ui_sig1bar4on2;
lv_obj_t *ui_Label19;
lv_obj_t *ui_Image6;
lv_obj_t *ui_Image4;
lv_obj_t *ui_Image7;
lv_obj_t *ui_Label33;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label28;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Label98;
lv_obj_t *ui_Label29;
lv_obj_t *ui_P1Timer;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Label99;
lv_obj_t *ui_P1Split;
lv_obj_t *ui_Label12;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Label21;
lv_obj_t *ui_P1Dist;
lv_obj_t *ui_Label23;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Label24;
lv_obj_t *ui_P1Stroke;
lv_obj_t *ui_Label44;
lv_obj_t *ui_Label3;
lv_obj_t *ui_P1Speed;
lv_obj_t *ui_Label46;
lv_obj_t *ui_Label92;
lv_obj_t *ui_Label25;
lv_obj_t *ui_P1Power;
lv_obj_t *ui_Label48;
lv_obj_t *ui_Label97;
lv_obj_t *ui_Label26;
lv_obj_t *ui_P1HR;
lv_obj_t *ui_Label50;
lv_obj_t *ui_Label88;
lv_obj_t *ui_Label27;
lv_obj_t *ui_Label53;
lv_obj_t *ui_P8Dist;
lv_obj_t *ui_Label60;
lv_obj_t *ui_Label100;
lv_obj_t *ui_Label87;
lv_obj_t *ui_P8Stroke;
lv_obj_t *ui_Label64;
lv_obj_t *ui_Label94;
lv_obj_t *ui_P8Speed;
lv_obj_t *ui_Label68;
lv_obj_t *ui_Label93;
lv_obj_t *ui_Label11;
lv_obj_t *ui_P8Power;
lv_obj_t *ui_Label72;
lv_obj_t *ui_Label90;
lv_obj_t *ui_Label91;
lv_obj_t *ui_P8HR;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Label18;
lv_obj_t *ui_Label17;
lv_obj_t *ui_Label14;
lv_obj_t *ui_P8Timer;
lv_obj_t *ui_Label13;
lv_obj_t *ui_Label20;
lv_obj_t *ui_P8Split;
lv_obj_t *ui_Label54;
lv_obj_t *ui_Label55;
lv_obj_t *ui_Label56;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t *e);
lv_obj_t *ui_Screen2;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_Label31;
void ui_event_Button1(lv_event_t *e);
lv_obj_t *ui_Button1;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Panel8;
void ui_event_Button3(lv_event_t *e);
lv_obj_t *ui_Button3;
lv_obj_t *ui_Label37;
void ui_event_Button5(lv_event_t *e);
lv_obj_t *ui_Button5;
lv_obj_t *ui_Label38;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t *e);
lv_obj_t *ui_Screen3;
lv_obj_t *ui_Panel6;
lv_obj_t *ui_Label30;
void ui_event_Button4(lv_event_t *e);
lv_obj_t *ui_Button4;
lv_obj_t *ui_Label22;
lv_obj_t *ui_Panel9;
lv_obj_t *ui_uiBTListContainer;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t *e);
lv_obj_t *ui_Screen4;
lv_obj_t *ui_Panel7;
lv_obj_t *ui_Label36;
void ui_event_Button6(lv_event_t *e);
lv_obj_t *ui_Button6;
lv_obj_t *ui_Label34;
lv_obj_t *ui_Panel10;
lv_obj_t *ui_Panel13;
lv_obj_t *ui_Label39;
lv_obj_t *ui_Label80;
lv_obj_t *ui_Panel14;
lv_obj_t *ui_Label41;
lv_obj_t *ui_Label81;
lv_obj_t *ui_Panel15;
lv_obj_t *ui_Label42;
lv_obj_t *ui_Label82;
lv_obj_t *ui_Panel16;
lv_obj_t *ui_Label89;
lv_obj_t *ui_Label83;
lv_obj_t *ui_Panel17;
lv_obj_t *ui_Label45;
lv_obj_t *ui_Label84;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t *ui_imgset_ble[1] = {&ui_img_ble1_png};
const lv_img_dsc_t *ui_imgset_jieli[1] = {&ui_img_jieli1_png};
const lv_img_dsc_t *ui_imgset_satellite[1] = {&ui_img_satellite2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_GESTURE &&
      lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
    lv_indev_wait_release(lv_indev_get_act());
    _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &ui_Screen2_screen_init);
  }
}

void ui_event_Screen2(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_GESTURE &&
      lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
    lv_indev_wait_release(lv_indev_get_act());
    _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0,
                      &ui_Screen1_screen_init);
  }
}

void ui_event_Button1(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &ui_Screen1_screen_init);
  }
}

void ui_event_Button3(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &ui_Screen3_screen_init);
  }
}

void ui_event_Button5(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &ui_Screen4_screen_init);
  }
}

void ui_event_Screen3(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_GESTURE &&
      lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
    lv_indev_wait_release(lv_indev_get_act());
    _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0,
                      &ui_Screen2_screen_init);
  }
}

void ui_event_Button4(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &ui_Screen2_screen_init);
  }
}

void ui_event_Screen4(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_GESTURE &&
      lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
    lv_indev_wait_release(lv_indev_get_act());
    _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0,
                      &ui_Screen2_screen_init);
  }
}

void ui_event_Button6(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &ui_Screen2_screen_init);
  }
}

///////////////////// SCREENS ////////////////////

void ui_init(void) {
  LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

  lv_disp_t *dispp = lv_disp_get_default();
  lv_theme_t *theme = lv_theme_default_init(
      dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
      false, LV_FONT_DEFAULT);
  lv_disp_set_theme(dispp, theme);
  ui_Screen1_screen_init();
  ui_Screen2_screen_init();
  ui_Screen3_screen_init();
  ui_Screen4_screen_init();
  ui____initial_actions0 = lv_obj_create(NULL);
  lv_disp_load_scr(ui_Screen1);
}
