// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: rowing480320

#ifndef _UI_COMP_BUTTON2_H
#define _UI_COMP_BUTTON2_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Button2
#define UI_COMP_BUTTON2_BUTTON2 0
#define UI_COMP_BUTTON2_LABEL35 1
#define _UI_COMP_BUTTON2_NUM 2
lv_obj_t * ui_Button2_create(lv_obj_t * comp_parent);
void ui_event_comp_Button2_Button2(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
