// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: rowing480320

#include "../ui.h"

void ui_comp_Button2_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Button3_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Panel4_create_hook(lv_obj_t * comp)
{
}
