// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: rowing480320

#include "../ui.h"


void ui_event_comp_Button2_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_Button2 = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen3_screen_init);
    }
}

// COMPONENT Button2

lv_obj_t * ui_Button2_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Button2;
    cui_Button2 = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_Button2, 380);
    lv_obj_set_height(cui_Button2, 50);
    lv_obj_set_x(cui_Button2, 0);
    lv_obj_set_y(cui_Button2, -79);
    lv_obj_set_align(cui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_state(cui_Button2, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(cui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(cui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(cui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_Button2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(cui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(cui_Button2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_t * cui_Label35;
    cui_Label35 = lv_label_create(cui_Button2);
    lv_obj_set_width(cui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label35, -130);
    lv_obj_set_y(cui_Label35, 0);
    lv_obj_set_align(cui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label35, "蓝牙列表");
    lv_obj_set_style_text_color(cui_Label35, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label35, &ui_font_Font24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON2_NUM);
    children[UI_COMP_BUTTON2_BUTTON2] = cui_Button2;
    children[UI_COMP_BUTTON2_LABEL35] = cui_Label35;
    lv_obj_add_event_cb(cui_Button2, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Button2, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_Button2, ui_event_comp_Button2_Button2, LV_EVENT_ALL, children);
    ui_comp_Button2_create_hook(cui_Button2);
    return cui_Button2;
}

