// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: rowing480320

#ifndef _UI_COMP_BUTTON3_H
#define _UI_COMP_BUTTON3_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Button3
#define UI_COMP_BUTTON3_BUTTON3 0
#define UI_COMP_BUTTON3_LABEL37 1
#define _UI_COMP_BUTTON3_NUM 2
lv_obj_t * ui_Button3_create(lv_obj_t * comp_parent);
void ui_event_comp_Button3_Button3(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
