// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: rowing480320

#include "../ui.h"


void ui_event_comp_Button3_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_Button3 = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen3_screen_init);
    }
}

// COMPONENT Button3

lv_obj_t * ui_Button3_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Button3;
    cui_Button3 = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_Button3, 380);
    lv_obj_set_height(cui_Button3, 50);
    lv_obj_set_x(cui_Button3, 0);
    lv_obj_set_y(cui_Button3, -79);
    lv_obj_set_align(cui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(cui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(cui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_Button3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(cui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(cui_Button3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_t * cui_Label37;
    cui_Label37 = lv_label_create(cui_Button3);
    lv_obj_set_width(cui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label37, -130);
    lv_obj_set_y(cui_Label37, 0);
    lv_obj_set_align(cui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label37, "蓝牙列表");
    lv_obj_set_style_text_color(cui_Label37, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label37, &ui_font_Font24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(cui_Label37, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(cui_Label37, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_font(cui_Label37, &ui_font_Font24, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON3_NUM);
    children[UI_COMP_BUTTON3_BUTTON3] = cui_Button3;
    children[UI_COMP_BUTTON3_LABEL37] = cui_Label37;
    lv_obj_add_event_cb(cui_Button3, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Button3, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_Button3, ui_event_comp_Button3_Button3, LV_EVENT_ALL, children);
    ui_comp_Button3_create_hook(cui_Button3);
    return cui_Button3;
}

